version: '3'
services:
  order-service:
    build:
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
  db:
    image: postgis/postgis:latest
    ports:
      - "5434:5434"
    networks:
      - my-network
    environment:
      POSTGRES_DB: liga-d
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

networks:
  my-network: