version: '3'
services:
  delivery-service:
    build:
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin

  db:
    image: postgres:16
    ports:
      - 5434:5434
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
