package ru.liga.enums;

import lombok.NoArgsConstructor;

@NoArgsConstructor
public enum OrderStatus {
    CUSTOMER_CREATED,
    CUSTOMER_PAID,
    CUSTOMER_CANCELLED,
    KITCHEN_ACCEPTED,
    KITCHEN_DENIED,
    KITCHEN_COMPLETE,
    KITCHEN_REFUNDED,
    DELIVERY_PENDING,
    DELIVERY_PICKING,
    DELIVERY_DENIED,
    DELIVERY_DELIVERING,
    DELIVERY_REFUNDED,
    DELIVERY_COMPLETE
}
