version: '3'
services:
  order-service:

    build:
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
  db:
    image: postgis/postgis
    ports:
      - "5435:5435"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
