server:
  port: 8082

spring:
  application:
    name: kitchen-service
  cloud:
    gateway:
      routes:
        - id: kitchen-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/kitchen/**
          filters:
            - TokenRelay
            - RemoveRequestHeader=Cookie
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
      org:
        hibernate:
          envers:
            revision_field_name: rev_id
            revision_type_field_name: rev_type
    show-sql: 'true'
  datasource:
    password: 'admin'
    url: jdbc:postgresql://localhost:5432/postgres
    username: 'admin'
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  endpoint:
    health:
      show-details: ALWAYS
